### ISSUE TITLE
"Apply heightmap and save" gives crazy output

### ISSUE THREAD

**Issue by Envergure** [martin2250/GrblHeightProbe2#10]
I have a random little Gcode file I'm using for tests.  It was generated in MakerCAM.  When I apply a heightmap to it using GrblHeightProbe v2.3, the output toolpath is quite different from the input.
![height probe before-after](https://cloud.githubusercontent.com/assets/14314362/10182379/84b9a500-66f1-11e5-96e7-8c1b1818b1c8.png)
The original toolpath (left) looks correct and I've successfully carved the part already.  Applying the heightmap causes the curved sections of the path to become misshapen (centre).  I haven't yet tried sending this output file to my machine.  UGS disagrees with GHP2 as to the diameter of some of the arcs (right).

I tried to attach the heightmap and Gcode files to this post, but GitHub won't accept them :(

**Comment by martin2250** [comment]
MakerCAM often produces rather bad G-Code, it uses many subsections for arcs and sometimes the center doesn't match up completely with the initial and final position.  
Can you try using version 2.2? I've made some changes to the GCode parser. You can upload the GCode to pastebin (even anonymously) or as a GitHub gist and just link it in here.

**Comment by Envergure** [comment]
Version 2.2 gives the same result.

Here are the files:  https://gist.github.com/Envergure/17b4d43f75ccfddb8a48

I'll try starting from scratch with a different CAM program.

**Comment by Envergure** [comment]
I've tried again, this time using gcode generated by the GCodeTools extension for Inkscape.  The result was similar.
![grbl height probe before-after 2](https://cloud.githubusercontent.com/assets/14314362/10211023/8374de6e-67bc-11e5-9476-944887771abb.png)

**Comment by martin2250** [comment]
Thanks for the confirmation, I'll look into it

**Comment by martin2250** [comment]
I had a mistake in a single line which caused arcs to be messed up, I'm just uploading release v2.3.1 which should work properly now.

**Comment by Envergure** [comment]
v2.3.1 is working perfectly on all the gcode files I tried before, both MakerCAM and GCodeTools.  Thanks so much!

**Comment by martin2250** [comment]
Great to hear that, I don't know how this even made it through so many versions without being noticed. I guess I only ever used it for pcb-gcode generated files which only use straight lines, but I remeber testing it with a pretty big makercam file as well.
