### ISSUE TITLE
Not alawed to restart work after probe failure

### ISSUE THREAD

**Issue by eliasg13** [martin2250/GrblHeightProbe2#12]
After one failure with the probing (due a defective conection to the pcb) the probing cant restart from where it lef. Lost about 30 minutes of probing as it ocurred when it came to the same corner where the conection was made. Is any chance to alaw the program to continue from the previus ok point?

**Comment by martin2250** [comment]
If a probe fails, grbl enters the 'Alarm' state, which inhibits all motion to prevent damage to the machine/part. To go back to 'Idle', you have to send grbl a '$X' command.  
I'm not sure if the position is still accurate after that, but I'd think so.  
If nothing works, you can save the HeightMap to a file, close the program, reset and reconnect grbl and load the HeightMap again. You can continue from a file.  
In any case, be sure to re-zero your machine (especially important for Z-axis)
