### ISSUE TITLE
GrblHeightProbe2 

### ISSUE THREAD

**Issue by sparkiedave123** [martin2250/GrblHeightProbe2#14]
After compiling on windows 7 the command dropdown menu does not appear,
then program crashes when you hit the Start/resume probing button.

**Comment by martin2250** [comment]
I removed the command / manual console entry and moved the console to the lower half of the main window.
As for the crash, can you run it with debugging in VS and post the exact exception?

**Comment by sparkiedave123** [comment]
Ok i understand now.

This is how i use your program.

Windows 7
Arduino mega with attached script

1/ open program (your latest .exe version)
2/ Connection , open com5 (coms now established).
3/ HeightMap, new, create
4/ >Start/resume Probing.
5 / program crashes (<Idle>) shown in command window
6/ see attached image.

**Comment by martin2250** [comment]
There is no attached image. Can you tell me in which line the format exception occured and maybe which string it received? That should help a lot. Also, which version of grbl are you using?

**Comment by sparkiedave123** [comment]
Sorry for the confusion.
My mistake for not following your u tube video.
working fine.
Thank you for your brill program

**Comment by martin2250** [comment]
Great that it's working again! Can you tell me what the problem was? Maybe I can warn people about it when I finally start the wiki.

**Comment by sparkiedave123** [comment]
It was just my silly mistake not following the correct procedures in the program.
Nothing wrong with it.
Thanks for a great program.
One suggestion , could you include  a machine controller i.e. X,Y,Z  in steps and jog so that you can move the axis without having to type in the G codes manually.

**Comment by martin2250** [comment]
Thanks for the suggestion, but I don't think I'll include a jogging feature.
When I have some free time again, I'll continue working on my other project which will integrate autolevelling in a mix-up of EMC/MACH and UGS
