### ISSUE TITLE
Program fails to open

### ISSUE THREAD

**Issue by Zwcky101** [martin2250/GrblHeightProbe2#20]
Program fails at startup it doesn't even open at all. Instantly goes to a program is not responding message.  How do I fix this.

**Comment by martin2250** [comment]
Hi,  
sounds like a pretty strange issue, I can only guess that .NET Framework 4.5 is missing.
Do you have any way to build the project from source and debug the issue?

**Comment by Zwcky101** [comment]
I'm going to try installing .NET Framework 4.5 and see if that fixes it.

**Comment by Zwcky101** [comment]
Got it working thanks

**Comment by martin2250** [comment]
Great to hear that!
