### ISSUE TITLE
Doesnt work with Machine 0,0 in top right

### ISSUE THREAD

**Issue by tekadept** [martin2250/GrblHeightProbe2#21]
My machine has is homed top right of machine, and workpiece goes down into negatives, whenever I try and run the tool it tries to go a positive value. 
Is there a way a switch can be put in for machines such as this?

**Comment by martin2250** [comment]
no, not neccessary:
when it asks you for the coordinates of the bottom-left point, just enter negative coordinates.

**Comment by tekadept** [comment]
Thanks I have the probing part working now.
